### ISSUE TITLE
Failed test at t/Taxonomy.t

### ISSUE THREAD

**Issue by emollier** [bioperl/Bio-DB-NCBIHelper#6]
Greetings,

While investigating [Debian Bug#983239](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=983239), I tried running the test suite straight from _origin/master_ and obtained the following output:

```
$ prove
t/EntrezGene.t ..... ok   
t/GenBank.t ........ ok     
t/GenPept.t ........ ok     
t/Query-Genbank.t .. ok     
t/RefSeq.t ......... ok   
t/Taxonomy.t ....... 43/? 
#   Failed test at t/Taxonomy.t line 102.
#          got: 'Actinomycetia'
#     expected: 'Actinobacteria'
t/Taxonomy.t ....... 69/? # Looks like you failed 1 test of 69.
t/Taxonomy.t ....... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/69 subtests 

Test Summary Report
-------------------
t/Taxonomy.t     (Wstat: 256 Tests: 69 Failed: 1)
  Failed test:  44
  Non-zero exit status: 1
Files=6, Tests=166, 152 wallclock secs ( 0.04 usr  0.01 sys +  1.88 cusr  0.23 csys =  2.16 CPU)
Result: FAIL
```

Is it possible the source NCBI database had some kind of shift recently?

Kind Regards,
Étienne.

**Comment by cjfields** [comment]
Hi @emollier a recent pull request from @MrCurtis addressed this (see history above).  This has been pushed out to CPAN in release 1.7.7.  Thanks for reporting!

**Comment by alexey-larionov** [comment]
The error is still here in 1.7.7 on 10 May 2022

**Comment by philgoetz** [comment]
> The error is still here in 1.7.7 on 10 May 2022

NCBI changed the database again, including:

- Actinomycetia => Actinomycetes
- homo sapiens no longer has the common name "man"; sorry to all you NLP programs out there
- 'Phygadeuon ovatus' formerly had no node, but now it's NCBI taxonomy node 2890685

Also, I changed the test for 'Trimorus ovatus' to 'Zaphod Beeblebrox', because you shouldn't test the functionality of reporting "No hit" for an actual species name, as it's likely to be added to the database eventually (as happened with P. ovatus).

I'll commit my fix here when I figure out how.

**Comment by cjfields** [comment]
We may want to consider how to future-proof these tests to not fail from remote database changes, though to be honest they don’t happen  often.

On Jan 25, 2023, at 1:31 PM, Phil Goetz ***@***.***> wrote:

﻿

The error is still here in 1.7.7 on 10 May 2022

NCBI changed the database again, including:

  *   Actinomycetia => Actinomycetes
  *   homo sapiens no longer has the common name "man"; sorry to all you NLP programs out there
  *   'Phygadeuon ovatus' formerly had no node, but now it's NCBI taxonomy node 2890685

Also, I changed the test for 'Trimorus ovatus' to 'Zaphod Beeblebrox', because you shouldn't test the functionality of reporting "No hit" for an actual species name, as it's likely to be added to the database eventually (as happened with P. ovatus).

I'll commit my fix here when I figure out how.

**Comment by esiefker** [comment]
I'm still seeing this bug a year and a half since it was closed.  Is there a workaround?  Or has this package just been impossible to install?

```

t/Taxonomy.t ........... 7/?
#   Failed test at t/Taxonomy.t line 48.
t/Taxonomy.t ........... 43/?
#   Failed test at t/Taxonomy.t line 102.
#          got: 'Actinomycetes'
#     expected: 'Actinomycetia'
t/Taxonomy.t ........... 68/?
#   Failed test 'Correct: No hit'
#   at t/Taxonomy.t line 181.
#          got: '2890685'
#     expected: 'No hit'
t/Taxonomy.t ........... 69/? # Looks like you failed 3 tests of 69.
```

**Comment by cjfields** [comment]
Hi @esiefker sorry, I haven't been seeing notifications for this repo so I'm glad you replied back.  To be honest I'm happy it still works, even though the tests have been failing.  Let me see what I can do to address this.

**Comment by philgoetz** [comment]
I committed my fixes, and got this message:

You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork philgoetz/Bio-DB-NCBIHelper, so you can send a pull request.

Is that sufficient for someone with write privs to move my changes into the main branch?

**Comment by carandraug** [comment]
> Is that sufficient for someone with write privs to move my changes into the main branch?

I think I found the patch on your github clone. I'll take care of merging it, give me a few minutes.

**Comment by carandraug** [comment]
@philgoetz I've split your fix into separate commits and pushed them.

I'm closing this issue (but someone else should test it and make a new release).

**Comment by cjfields** [comment]
@carandraug I'll set up tests and make a new release, thanks for the merge!

**Comment by cjfields** [comment]
@philgoetz @esiefker v1.7.8 has been pushed to CPAN.  It will take a little while to show up, but should be ready pretty soon
